# Generated by Django 4.1.5 on 2023-02-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mon_appli', '0002_alter_appointment_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='coach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mon_appli.coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='auth.group'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
