# Generated by Django 4.1.5 on 2023-02-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_appli', '0003_remove_coach_coach_id_appointment_coach_coach_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
