# Generated by Django 4.1.5 on 2023-02-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mon_appli', '0004_coach_coach_id_alter_coach_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mon_appli.coach'),
        ),
    ]
