# Generated by Django 4.1.5 on 2023-02-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_appli', '0005_alter_appointment_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
