# Generated by Django 4.1.5 on 2023-02-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_appli', '0006_remove_coach_groups_remove_coach_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='coach',
        ),
    ]
